// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdzlfcxsbidwvauzorad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkemxmY3hzYmlkd3ZhdXpvcmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODg4NTcsImV4cCI6MjA3MzU2NDg1N30.Rj7-mJosH4ExHaX4r6DKUHyjuXscQwI-68h1RsdIyEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});